import type { Metadata } from "next";
import Link from "next/link";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import { ArrowLeft, ArrowRight } from "lucide-react";
import JsonLd, { blogPostingSchema, breadcrumbSchema } from "@/components/JsonLd";

export const metadata: Metadata = {
  title: "Why Every Small Business Needs Multi-Factor Authentication (And How to Set It Up) | Copper Bay Tech",
  description:
    "95% of account takeovers rely on stolen passwords alone. MFA stops them. Here's what it is, why it matters, and how to turn it on in under 10 minutes.",
  alternates: { canonical: "https://copperbaytech.com/blog/why-your-business-needs-mfa" },
  openGraph: {
    title: "Why Every Small Business Needs Multi-Factor Authentication (And How to Set It Up)",
    description:
      "95% of account takeovers rely on stolen passwords alone. MFA stops them. Here's what it is, why it matters, and how to turn it on in under 10 minutes.",
    url: "https://copperbaytech.com/blog/why-your-business-needs-mfa",
    siteName: "Copper Bay Tech",
    type: "article",
    images: [{ url: "/og-image.png", width: 1200, height: 630 }],
  },
};

export default function Article() {
  return (
    <>
      <JsonLd schema={blogPostingSchema({ title: "Why Every Small Business Needs Multi-Factor Authentication (And How to Set It Up)", description: "95% of account takeovers rely on stolen passwords alone. MFA stops them. Here's what it is, why it matters, and how to turn it on in under 10 minutes.", url: "https://copperbaytech.com/blog/why-your-business-needs-mfa", datePublished: "2026-06-18" })} />
      <JsonLd schema={breadcrumbSchema([{ name: "Home", url: "https://copperbaytech.com" }, { name: "Blog", url: "https://copperbaytech.com/blog" }, { name: "Why Your Business Needs MFA" }])} />
      <Nav />
      <main>
        <section className="pt-32 pb-8 bg-[#18181B]">
          <div className="max-w-2xl mx-auto px-6">
            <Link
              href="/blog"
              className="inline-flex items-center gap-2 text-sm text-white/40 hover:text-white/70 transition-colors mb-8"
              style={{ fontFamily: "var(--font-heading)" }}
            >
              <ArrowLeft size={14} /> All Resources
            </Link>
            <span
              className="inline-block mb-4 px-3 py-1 rounded-md text-xs font-semibold uppercase tracking-widest"
              style={{
                backgroundColor: "rgba(249,115,22,0.15)",
                color: "#F97316",
                fontFamily: "var(--font-heading)",
              }}
            >
              Cybersecurity
            </span>
            <h1
              className="text-3xl md:text-4xl font-bold text-white mb-4 leading-tight"
              style={{ fontFamily: "var(--font-heading)" }}
            >
              Why Every Small Business Needs Multi-Factor Authentication (And How to Set It Up)
            </h1>
            <p className="text-white/50 text-sm" style={{ fontFamily: "var(--font-body)" }}>
              4 min read · June 2026
            </p>
          </div>
        </section>

        <section className="py-12 bg-white">
          <div className="max-w-2xl mx-auto px-6" style={{ fontFamily: "var(--font-body)" }}>
            <p className="text-lg text-[#3F3F46]/70 mb-6 leading-relaxed">
              Multi-factor authentication (MFA) means requiring something in addition to your password to log in — usually a short code sent to your phone or generated by an app. Even if a hacker has your password, they can&apos;t get in without that second factor. It&apos;s one of the simplest, highest-impact security measures you can implement — and most businesses haven&apos;t done it.
            </p>

            <h2
              className="text-2xl font-bold text-[#18181B] mt-10 mb-4"
              style={{ fontFamily: "var(--font-heading)" }}
            >
              Why it matters
            </h2>
            <p className="text-[#3F3F46]/70 mb-4 leading-relaxed">
              According to Microsoft, 95% of account takeover attacks rely on stolen or guessed passwords alone. Passwords get leaked in data breaches constantly — there&apos;s a decent chance yours have been exposed already (you can check at haveibeenpwned.com). If someone has your email and password, they can log into your email, your cloud storage, your banking — anything that uses the same credentials.
            </p>
            <p className="text-[#3F3F46]/70 mb-8 leading-relaxed">
              MFA stops this attack almost entirely. Even a leaked password becomes worthless without the second factor. Microsoft reports that MFA blocks 99.9% of automated account attacks. It&apos;s not a cure-all, but it&apos;s the highest-ROI security measure most small businesses can implement.
            </p>

            <h2
              className="text-2xl font-bold text-[#18181B] mt-10 mb-4"
              style={{ fontFamily: "var(--font-heading)" }}
            >
              Where to enable it first
            </h2>
            <p className="text-[#3F3F46]/70 mb-4 leading-relaxed">
              Don&apos;t try to enable MFA everywhere at once. Start with the accounts that matter most:
            </p>
            <div className="space-y-3 mb-8">
              {[
                { account: "Business email", why: "Your email is the master key — it can reset nearly every other account. This is the most important one." },
                { account: "Cloud storage", why: "Google Drive, Dropbox, OneDrive — if client files or financial data live here, it needs MFA." },
                { account: "Banking and payroll", why: "Most banks offer MFA. If yours does, enable it immediately." },
                { account: "Remote access tools", why: "VPNs, remote desktop tools, and anything that allows access to your internal systems from outside." },
                { account: "Domain registrar", why: "If someone hijacks your domain, they can redirect your website and email. Protect it." },
              ].map(({ account, why }) => (
                <div
                  key={account}
                  className="rounded-xl border border-[#18181B]/10 p-5 bg-[#FAFAF9]"
                >
                  <p
                    className="font-semibold text-[#18181B] text-sm mb-1"
                    style={{ fontFamily: "var(--font-heading)" }}
                  >
                    {account}
                  </p>
                  <p className="text-sm text-[#3F3F46]/60 leading-relaxed">{why}</p>
                </div>
              ))}
            </div>

            <h2
              className="text-2xl font-bold text-[#18181B] mt-10 mb-4"
              style={{ fontFamily: "var(--font-heading)" }}
            >
              How to set it up
            </h2>
            <p
              className="font-semibold text-[#18181B] mb-2"
              style={{ fontFamily: "var(--font-heading)" }}
            >
              Google Workspace
            </p>
            <p className="text-[#3F3F46]/70 mb-4 leading-relaxed">
              Go to admin.google.com → Security → 2-Step Verification → Allow users to turn on 2-Step Verification. Then enforce it: set Enforcement to &quot;On&quot; for all users. Users will be prompted on next login.
            </p>
            <p
              className="font-semibold text-[#18181B] mb-2"
              style={{ fontFamily: "var(--font-heading)" }}
            >
              Microsoft 365
            </p>
            <p className="text-[#3F3F46]/70 mb-4 leading-relaxed">
              Go to admin.microsoft.com → Settings → Org Settings → Security &amp; Privacy → Multi-factor authentication. Enable Security Defaults (the quickest option) or use Conditional Access for more control. Users will be prompted to register their second factor on next login.
            </p>
            <p
              className="font-semibold text-[#18181B] mb-2"
              style={{ fontFamily: "var(--font-heading)" }}
            >
              Generic accounts (most websites)
            </p>
            <p className="text-[#3F3F46]/70 mb-8 leading-relaxed">
              Most services have MFA in Settings → Security or Settings → Account. Look for &quot;Two-factor authentication,&quot; &quot;2-Step Verification,&quot; or &quot;Multi-factor authentication.&quot; You&apos;ll typically be given the option to use an authenticator app (recommended) or SMS codes. An app like Google Authenticator or Authy is more secure than SMS.
            </p>

            <h2
              className="text-2xl font-bold text-[#18181B] mt-10 mb-4"
              style={{ fontFamily: "var(--font-heading)" }}
            >
              Common objections — answered
            </h2>
            <div className="space-y-4 mb-8">
              {[
                {
                  objection: "\"It's too annoying.\"",
                  answer: "Most MFA prompts appear once per device, not every login. Once set up, it adds about 5 seconds to a login you do once a day. The 5 seconds is worth not having your email hijacked.",
                },
                {
                  objection: "\"We're too small to be targeted.\"",
                  answer: "Automated attacks don't discriminate by business size — they scan for weak accounts at scale. Small businesses are often easier targets precisely because they assume they're not at risk.",
                },
                {
                  objection: "\"What if I lose my phone?\"",
                  answer: "Most MFA systems have backup codes you can save offline. Keep them in a secure location. If you lose your phone, use a backup code while you get a replacement.",
                },
              ].map(({ objection, answer }) => (
                <div
                  key={objection}
                  className="rounded-xl border border-[#18181B]/10 p-5 bg-[#FAFAF9]"
                >
                  <p
                    className="font-semibold text-[#18181B] text-sm mb-2"
                    style={{ fontFamily: "var(--font-heading)" }}
                  >
                    {objection}
                  </p>
                  <p className="text-sm text-[#3F3F46]/60 leading-relaxed">{answer}</p>
                </div>
              ))}
            </div>

            <div className="mt-10 p-6 rounded-2xl bg-[#18181B] text-white">
              <p
                className="text-sm font-semibold mb-2 text-[#F97316]"
                style={{ fontFamily: "var(--font-heading)" }}
              >
                Want to know where else you&apos;re exposed?
              </p>
              <p className="text-sm text-white/70">
                A free security audit covers your full attack surface — not just MFA. We&apos;ll give you a prioritized list of what to fix first, with no obligation.
              </p>
            </div>

            <div className="mt-10 pt-8 border-t border-[#18181B]/10 flex flex-col sm:flex-row gap-4 items-center justify-between">
              <Link
                href="/blog"
                className="inline-flex items-center gap-2 text-sm text-[#3F3F46]/50 hover:text-[#18181B] transition-colors"
                style={{ fontFamily: "var(--font-heading)" }}
              >
                <ArrowLeft size={14} /> Back to Resources
              </Link>
              <Link
                href="/#contact"
                className="inline-flex items-center gap-2 px-6 py-3 rounded-md text-sm font-semibold text-white bg-[#F97316] hover:bg-[#ea6c0a] transition-colors"
                style={{ fontFamily: "var(--font-heading)" }}
              >
                Get a Free Security Audit <ArrowRight size={14} />
              </Link>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
