import type { Metadata } from "next";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Privacy Policy | Copper Bay Tech",
  description:
    "How Copper Bay Tech collects, uses, and protects information submitted through this website.",
};

export default function PrivacyPage() {
  return (
    <>
      <Nav />
      <main className="bg-[#FAFAF9] min-h-screen">
        {/* Hero */}
        <section className="pt-32 pb-12 bg-white border-b border-[#18181B]/10">
          <div className="max-w-3xl mx-auto px-6">
            <p
              className="text-xs font-semibold uppercase tracking-widest mb-3"
              style={{ color: "#F97316", fontFamily: "var(--font-heading)" }}
            >
              Legal
            </p>
            <h1
              className="text-4xl md:text-5xl font-bold mb-4 leading-tight"
              style={{ color: "#18181B", fontFamily: "var(--font-heading)" }}
            >
              Privacy Policy
            </h1>
            <p
              className="text-sm"
              style={{ color: "#3F3F46", fontFamily: "var(--font-body)", opacity: 0.6 }}
            >
              Last updated: May 31, 2026
            </p>
          </div>
        </section>

        {/* Body */}
        <section className="py-16">
          <div className="max-w-3xl mx-auto px-6">
            <div
              className="space-y-10 text-base leading-relaxed"
              style={{ color: "#3F3F46", fontFamily: "var(--font-body)" }}
            >
              {/* Intro */}
              <div>
                <p>
                  Copper Bay Tech ("we," "us," or "our") is a founder-led IT consulting, web development, and
                  cybersecurity company based in Petaluma, California. This Privacy Policy explains what
                  information we collect when you visit{" "}
                  <span style={{ fontFamily: "var(--font-heading)", color: "#18181B" }}>
                    copperbaytech.com
                  </span>
                  , how we use it, and your rights with respect to that information.
                </p>
                <p className="mt-4">
                  We do not sell, rent, or trade your personal information — ever. This site exists to help
                  Sonoma County businesses learn about our services and get in touch. Nothing more.
                </p>
              </div>

              {/* Section 1 */}
              <div>
                <h2
                  className="text-xl font-bold mb-4"
                  style={{ color: "#18181B", fontFamily: "var(--font-heading)" }}
                >
                  1. Information We Collect
                </h2>
                <p className="mb-4">
                  We collect information only in the following limited ways:
                </p>
                <ul className="list-disc pl-6 space-y-3">
                  <li>
                    <span style={{ fontFamily: "var(--font-heading)", fontWeight: 600, color: "#18181B" }}>
                      Contact form submissions.
                    </span>{" "}
                    When you fill out our contact form, we collect the fields you provide: your name, business
                    name, email address, phone number, and message. This information is used solely to respond
                    to your inquiry.
                  </li>
                  <li>
                    <span style={{ fontFamily: "var(--font-heading)", fontWeight: 600, color: "#18181B" }}>
                      Website audit / health-check tool.
                    </span>{" "}
                    Our free website audit tool only processes the URL you submit. It queries third-party APIs
                    (such as Google PageSpeed Insights) to return publicly available performance data about
                    that URL. We do not store the URL you submit, the results returned, or any other
                    information generated by using this tool.
                  </li>
                  <li>
                    <span style={{ fontFamily: "var(--font-heading)", fontWeight: 600, color: "#18181B" }}>
                      Basic analytics and usage data.
                    </span>{" "}
                    We may collect anonymized, aggregated information about how visitors use this site —
                    such as pages viewed and general geographic region — to understand what content is most
                    useful. This data is not tied to any individual and does not identify you personally.
                  </li>
                </ul>
                <p className="mt-4">
                  We do <em>not</em> collect payment information on this website. Any engagement requiring
                  payment is handled through a separate, signed agreement outside of this site.
                </p>
              </div>

              {/* Section 2 */}
              <div>
                <h2
                  className="text-xl font-bold mb-4"
                  style={{ color: "#18181B", fontFamily: "var(--font-heading)" }}
                >
                  2. How We Use Your Information
                </h2>
                <ul className="list-disc pl-6 space-y-3">
                  <li>
                    To respond to your questions and consultation requests submitted through the contact form.
                  </li>
                  <li>
                    To deliver the results of the free website audit tool to you in your browser session.
                  </li>
                  <li>
                    To understand overall site usage patterns and improve the content we publish.
                  </li>
                </ul>
                <p className="mt-4">
                  We do not use your information for advertising, and we do not build marketing profiles on
                  visitors to this site.
                </p>
              </div>

              {/* Section 3 */}
              <div>
                <h2
                  className="text-xl font-bold mb-4"
                  style={{ color: "#18181B", fontFamily: "var(--font-heading)" }}
                >
                  3. Cookies &amp; Analytics
                </h2>
                <p className="mb-4">
                  This site may use minimal, privacy-respecting cookies necessary for basic site functionality.
                  We do not currently use third-party advertising cookies or cross-site tracking cookies.
                </p>
                <p>
                  If we adopt analytics software, it will be configured to anonymize IP addresses and avoid
                  the collection of personally identifiable information. We will update this policy if our
                  analytics approach changes materially.
                </p>
              </div>

              {/* Section 4 */}
              <div>
                <h2
                  className="text-xl font-bold mb-4"
                  style={{ color: "#18181B", fontFamily: "var(--font-heading)" }}
                >
                  4. Third-Party Services
                </h2>
                <p className="mb-4">
                  To operate this website, we use the following third-party services:
                </p>
                <ul className="list-disc pl-6 space-y-3">
                  <li>
                    <span style={{ fontFamily: "var(--font-heading)", fontWeight: 600, color: "#18181B" }}>
                      Resend.
                    </span>{" "}
                    When you submit the contact form, your name, email, phone number, business name, and
                    message are transmitted to{" "}
                    <a
                      href="https://resend.com"
                      target="_blank"
                      rel="noopener noreferrer"
                      style={{ color: "#F97316" }}
                    >
                      Resend
                    </a>
                    , a transactional email delivery service, so the message can be forwarded to us.
                    Resend processes this data solely to deliver the email on our behalf.
                  </li>
                  <li>
                    <span style={{ fontFamily: "var(--font-heading)", fontWeight: 600, color: "#18181B" }}>
                      Hosting provider.
                    </span>{" "}
                    This site is hosted on a third-party infrastructure provider. Standard server logs (IP
                    addresses, request timestamps, pages accessed) may be retained by the host for security
                    and diagnostic purposes, typically for a short period in accordance with their policies.
                  </li>
                  <li>
                    <span style={{ fontFamily: "var(--font-heading)", fontWeight: 600, color: "#18181B" }}>
                      Google PageSpeed Insights API.
                    </span>{" "}
                    Our free website audit tool uses the Google PageSpeed Insights API to retrieve performance
                    data for the URL you provide. The URL you submit is sent to Google as part of that API
                    request. Google's use of that data is governed by{" "}
                    <a
                      href="https://policies.google.com/privacy"
                      target="_blank"
                      rel="noopener noreferrer"
                      style={{ color: "#F97316" }}
                    >
                      Google's Privacy Policy
                    </a>
                    .
                  </li>
                </ul>
                <p className="mt-4">
                  We do not share your personal information with any other third parties except as required
                  by law or as necessary to operate the services described above.
                </p>
              </div>

              {/* Section 5 */}
              <div>
                <h2
                  className="text-xl font-bold mb-4"
                  style={{ color: "#18181B", fontFamily: "var(--font-heading)" }}
                >
                  5. Data Retention
                </h2>
                <p>
                  Contact form submissions are retained only as long as necessary to respond to your inquiry
                  and maintain a reasonable business record of that correspondence — typically no more than
                  two years, unless an ongoing client relationship requires longer retention. We do not
                  retain website audit tool inputs or outputs. Anonymized analytics data, if collected, may
                  be retained indefinitely in aggregate form.
                </p>
              </div>

              {/* Section 6 */}
              <div>
                <h2
                  className="text-xl font-bold mb-4"
                  style={{ color: "#18181B", fontFamily: "var(--font-heading)" }}
                >
                  6. Your Rights
                </h2>
                <p className="mb-4">
                  You have the right to request access to, correction of, or deletion of any personal
                  information we hold about you. To exercise any of these rights, contact us at the email
                  or phone number listed at the end of this policy.
                </p>
                <p className="mb-4">
                  <span style={{ fontFamily: "var(--font-heading)", fontWeight: 600, color: "#18181B" }}>
                    California Residents (CCPA).
                  </span>{" "}
                  As a California-based company serving California residents, we acknowledge your rights
                  under the California Consumer Privacy Act (CCPA). You have the right to know what personal
                  information we collect and how it is used, the right to request deletion of your personal
                  information, and the right to opt out of the sale of your personal information. We do not
                  sell personal information. To submit a request, contact us directly using the information
                  below.
                </p>
              </div>

              {/* Section 7 */}
              <div>
                <h2
                  className="text-xl font-bold mb-4"
                  style={{ color: "#18181B", fontFamily: "var(--font-heading)" }}
                >
                  7. Data Security
                </h2>
                <p>
                  We take reasonable technical and organizational precautions to protect the information
                  submitted through this site. Data transmitted via the contact form is sent over encrypted
                  HTTPS connections and handled by reputable third-party services with their own security
                  programs. No method of transmission or storage is 100% secure, and we cannot guarantee
                  absolute security. If you have concerns about a specific piece of information, please
                  contact us before submitting it through the site.
                </p>
              </div>

              {/* Section 8 */}
              <div>
                <h2
                  className="text-xl font-bold mb-4"
                  style={{ color: "#18181B", fontFamily: "var(--font-heading)" }}
                >
                  8. Children's Privacy
                </h2>
                <p>
                  This website is intended for business owners and professionals. We do not knowingly collect
                  personal information from anyone under 13 years of age. If you believe a child has
                  submitted personal information through this site, please contact us and we will delete it
                  promptly.
                </p>
              </div>

              {/* Section 9 */}
              <div>
                <h2
                  className="text-xl font-bold mb-4"
                  style={{ color: "#18181B", fontFamily: "var(--font-heading)" }}
                >
                  9. Changes to This Policy
                </h2>
                <p>
                  We may update this Privacy Policy from time to time to reflect changes in our practices or
                  applicable law. When we do, we will update the "last updated" date at the top of this page.
                  We encourage you to review this policy periodically. Continued use of the site after any
                  changes constitutes acceptance of the updated policy.
                </p>
              </div>

              {/* Section 10 */}
              <div>
                <h2
                  className="text-xl font-bold mb-4"
                  style={{ color: "#18181B", fontFamily: "var(--font-heading)" }}
                >
                  10. Contact Us
                </h2>
                <p className="mb-4">
                  If you have questions about this Privacy Policy or want to exercise your data rights,
                  please reach out:
                </p>
                <div
                  className="rounded-xl border border-[#18181B]/10 bg-white p-6 space-y-2"
                  style={{ fontFamily: "var(--font-heading)" }}
                >
                  <p className="font-bold text-[#18181B]">Copper Bay Tech</p>
                  <p>Petaluma, California</p>
                  <p>
                    Email:{" "}
                    <a
                      href="mailto:duke@copperbaytech.com"
                      style={{ color: "#F97316" }}
                    >
                      duke@copperbaytech.com
                    </a>
                  </p>
                  <p>
                    Phone:{" "}
                    <a
                      href="tel:+17072396725"
                      style={{ color: "#F97316" }}
                    >
                      (707) 239-6725
                    </a>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
